@baseUrl = http://localhost:3000

#Recados
### Lista todos os recados
GET {{baseUrl}}/recados/

### Lista apenas um recado
GET {{baseUrl}}/recados/2

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": " 2 Novo recado",
    "de": "Joana",
    "para": "João"
}

###
PATCH  {{baseUrl}}/recados/3
Content-Type: application/json

{
    "texto": "Recado novo",
    "lido": true
}

###
DELETE  {{baseUrl}}/recados/3/

### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploRota
GET {{baseUrl}}/home/exemplo

### ConceitosManualControllerHome

# @name ConceitosManualControllerHome

GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoControllerHome

# @name ConceitosAutomaticoControllerHome

GET {{baseUrl}}/conceitos-automatico/