@baseUrl = http://localhost:3000

#Recados
### Lista todos os recados
GET {{baseUrl}}/recados/

### Lista apenas um recado
GET {{baseUrl}}/recados/2

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado",
    "de": "Joana",
    "para": "João"
}

### Atualiza um recado
PATCH  {{baseUrl}}/recados/3
Content-Type: application/json

{
    "lido": false
}

### Deleta um recado
DELETE  {{baseUrl}}/recados/3/


#


#Pessoas
### Lista todas as pessoas
GET {{baseUrl}}/pessoas/

### Lista uma pessoa
GET {{baseUrl}}/pessoas/2

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "123456",
    "nome": "carlos"
}

### Atualiza uma pessoa
PATCH  {{baseUrl}}/pessoas/7
Content-Type: application/json

{
    "password": "654321",
    "nome": "João"
}

### Deleta uma pessoa
DELETE  {{baseUrl}}/pessoas/6/


#


### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploRota
GET {{baseUrl}}/home/exemplo

### ConceitosManualControllerHome

# @name ConceitosManualControllerHome

GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoControllerHome

# @name ConceitosAutomaticoControllerHome

GET {{baseUrl}}/conceitos-automatico/